// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkriCcWhvTO2iqqQj8waneCKz2Aqy_KT8',
    appId: '1:165158061886:web:a24390eb892c6102b58e6f',
    messagingSenderId: '165158061886',
    projectId: 'project-pab2',
    authDomain: 'project-pab2.firebaseapp.com',
    storageBucket: 'project-pab2.appspot.com',
    measurementId: 'G-KZ4344GWM3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNmqTx0gFtAr9lzFKOa-CzNOBuhxGtJTk',
    appId: '1:165158061886:android:372e86fcf15cfdfeb58e6f',
    messagingSenderId: '165158061886',
    projectId: 'project-pab2',
    storageBucket: 'project-pab2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkKbhVmUvq_bta7zoYthslcG30_pBaDn8',
    appId: '1:165158061886:ios:5bc1980e665f7f67b58e6f',
    messagingSenderId: '165158061886',
    projectId: 'project-pab2',
    storageBucket: 'project-pab2.appspot.com',
    iosClientId: '165158061886-hbp3phm4bm2s47rksirngd3bp3cld79v.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkKbhVmUvq_bta7zoYthslcG30_pBaDn8',
    appId: '1:165158061886:ios:5bc1980e665f7f67b58e6f',
    messagingSenderId: '165158061886',
    projectId: 'project-pab2',
    storageBucket: 'project-pab2.appspot.com',
    iosClientId: '165158061886-hbp3phm4bm2s47rksirngd3bp3cld79v.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectPab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkriCcWhvTO2iqqQj8waneCKz2Aqy_KT8',
    appId: '1:165158061886:web:ccff7c6b66346c53b58e6f',
    messagingSenderId: '165158061886',
    projectId: 'project-pab2',
    authDomain: 'project-pab2.firebaseapp.com',
    storageBucket: 'project-pab2.appspot.com',
    measurementId: 'G-8EF2BSRDLT',
  );

}